# -*- mode: ruby -*-
# vi: set ft=ruby :

MEMORY="1024"
CPUS="2"

MASTER="amalsagoS"
WORKER="amalsagoSW"

IP_MASTER="192.168.42.110"
IP_WORKER="192.168.42.111"

master_script = <<-SHELL
    echo "I am master"
    echo #{IP_MASTER} #{MASTER} >> /etc/hosts
    echo #{IP_WORKER} #{WORKER} >> /etc/hosts
    cat /etc/hosts
    SHELL

worker_script = <<-SHELL
    echo "I am master"
    echo #{IP_WORKER} #{WORKER} >> /etc/hosts
    echo #{IP_MASTER} #{MASTER} >> /etc/hosts
    cat /etc/hosts
    SHELL

Vagrant.configure("2") do | config |
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do | vb |
    vb.memory = MEMORY
    vb.cpus = CPUS

    # Enable NAT hosts DNS resolver
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # Reduce the time sync threshold
    vb.customize [ "guestproperty", "set", :id, "/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold", 10000 ]
  end

  config.vm.define MASTER do | master |
    master.vm.hostname = MASTER
    master.vm.network "private_network", ip: IP_MASTER
    master.vm.provision "shell", inline: master_script
    master.vm.synced_folder "./shared", "/vagrant_shared", type: "nfs"  
  end

  config.vm.define WORKER do | worker |
    worker.vm.hostname = WORKER
    worker.vm.network "private_network", ip: IP_WORKER
    worker.vm.provision "shell", inline: worker_script
    worker.vm.synced_folder "./shared", "/vagrant_shared", type: "nfs"  
  end
end
