CPUS = 4
MEMORY = 4096
BOX = "debian/buster64"

Vagrant.configure("2") do | config |
  config.vm.provider "virtualbox" do | vb |
    vb.cpus = CPUS
    vb.memory = MEMORY
  end
  
  config.vm.define "glab" do |gitlab|
  	gitlab.vm.network "forwarded_port", guest: 9999, host: 9999, protocol: "tcp"
    gitlab.vm.box = BOX
    gitlab.vm.hostname = "glab"
  	gitlab.vm.box_url = "debian/buster64"
	  gitlab.vm.network "private_network", ip: "192.168.42.99"
	  gitlab.vm.provision "shell", inline: <<-SHELL
		  sed -i 's/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g' /etc/ssh/sshd_config
		  service ssh restart
	  SHELL
	  gitlab.vm.provision "shell", path: "scripts/install_gitlab.sh", env: {"HOST_IP" => "#{ENV['HOST_IP']}"}
  end
end
